version: '3.8'

services:
  frontend:
    # In dev we explicitly mount node_modules as a named volume and
    # use a cached bind mount to improve performance where supported.
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - WATCHPACK_POLLING=true

volumes:
  frontend_node_modules:
